# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ccrider < Formula
  desc "Search, browse, and resume your Claude Code sessions"
  homepage "https://github.com/neilberkman/ccrider"
  version "0.1.0"
  license "MIT"

  depends_on "go" => :build
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/neilberkman/ccrider/releases/download/v0.1.0/ccrider_0.1.0_darwin_amd64.tar.gz"
    sha256 "a58fa1227eaee0549908fa396bdbd32d8681e65ea9d8c4ed81d7eb3ff079496c"

    def install
      bin.install "ccrider"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/neilberkman/ccrider/releases/download/v0.1.0/ccrider_0.1.0_darwin_arm64.tar.gz"
    sha256 "ba7f3279aba206c06efba50f5f60698ddd0c644bb51f5e239c34c89cd8d02817"

    def install
      bin.install "ccrider"
    end
  end

  test do
    system "#{bin}/ccrider", "--version"
  end
end
