# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ccrider < Formula
  desc "Search, browse, and resume your Claude Code sessions"
  homepage "https://github.com/neilberkman/ccrider"
  version "0.2.1"
  license "MIT"

  depends_on "go" => :build

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/neilberkman/ccrider/releases/download/v0.2.1/ccrider_0.2.1_darwin_amd64.tar.gz"
      sha256 "2d63b995308d056c7b6c5c99490d4a3f68a31926faf9330242ce77c59a6ab1a4"

      def install
        bin.install "ccrider"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/neilberkman/ccrider/releases/download/v0.2.1/ccrider_0.2.1_darwin_arm64.tar.gz"
      sha256 "989984f6989df2e484ccf118af2e23a968188c586d86c3d932599aa9122ae8a7"

      def install
        bin.install "ccrider"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/neilberkman/ccrider/releases/download/v0.2.1/ccrider_0.2.1_linux_amd64.tar.gz"
      sha256 "cb2a6b474e48eaa6b4a84ad12439bdc53272ee43071f2f8bb8cd7226d919f2b8"
      def install
        bin.install "ccrider"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/neilberkman/ccrider/releases/download/v0.2.1/ccrider_0.2.1_linux_arm64.tar.gz"
      sha256 "946394d0f2e3bb259bfdcfb21a9471652db8c292c7c8f9357084a0cd4e819763"
      def install
        bin.install "ccrider"
      end
    end
  end

  test do
    system "#{bin}/ccrider", "--version"
  end
end
