# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ccrider < Formula
  desc "Search, browse, and resume your Claude Code sessions"
  homepage "https://github.com/neilberkman/ccrider"
  version "0.2.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/neilberkman/ccrider/releases/download/v0.2.2/ccrider_0.2.2_darwin_amd64.tar.gz"
      sha256 "634941372ca7b51410e68c08e6c2adc48d9cdd366401f9c6a13c601422830ca1"

      def install
        bin.install "ccrider"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/neilberkman/ccrider/releases/download/v0.2.2/ccrider_0.2.2_darwin_arm64.tar.gz"
      sha256 "51fd46ff0ad46726c508be6e6ca0996c25bcab0f379492f363e5c1e7534e4611"

      def install
        bin.install "ccrider"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/neilberkman/ccrider/releases/download/v0.2.2/ccrider_0.2.2_linux_amd64.tar.gz"
      sha256 "127932f34d0482ec810f3d3cb5c9f97e0d7dfbc2ce1b77697a84e3ba7bc2c55a"
      def install
        bin.install "ccrider"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/neilberkman/ccrider/releases/download/v0.2.2/ccrider_0.2.2_linux_arm64.tar.gz"
      sha256 "af394dbd358f880c69d246a3ccfdb0c53dc18ecefac508b3ab16b1dfb31a6d14"
      def install
        bin.install "ccrider"
      end
    end
  end

  test do
    system "#{bin}/ccrider", "--version"
  end
end
